---
title: "Rapport échantillon de données Cancers IDF de la base Ameli"
author: "Audrey Difernand"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

## Création d'un rapport

Objectif : Créer un rapport en format HTML en utilisant les données importées dans DuckDB



```{r setup, include=FALSE}
# Chargement des packages nécessaires
knitr::opts_chunk$set(echo = TRUE)

library(DBI)
library(duckdb)
library(dplyr)
library(ggplot2)
library(gtsummary)
```


#### Connexion à la base DuckDB locale
```{r connexion}
con <- dbConnect(duckdb::duckdb(), dbdir = "ameli.duckdb", read_only = TRUE)
```
#### Vérification des tables disponibles
```{r tables_dispo}
tables <- dbListTables(con)
tables
```
#### Requête SQL : on récupère toutes les colonnes de la table cancers_idf
```{r requete}
query <- "SELECT * FROM cancers_idf "
```
#### Exécution de la requête
```{r base}
result <- dbGetQuery(con, query)
head(result,5)

```
#### Tableau descriptif

```{r table}

tbl <- result %>%
dplyr::select(dept, cla_age_5, niveau_prioritaire, sexe) %>%
gtsummary::tbl_summary(
by = dept, # regroupement principal par département
statistic = all_continuous() ~ "{mean} ({sd})",
digits = all_continuous() ~ 0,
missing = "no"
) %>%
add_n() %>% # ajoute le nombre total d'observations
modify_header(label ~ "Variable") %>%
modify_caption("Tableau descriptif par département, classe d'âge, sexe et niveau prioritaire")

tbl

```

